#import "../template/lib.typ" as template

= Introduction

In natural language processing (NLP), dependency parsing refers to the task of constructing sentence-level dependency trees. Syntactically, a dependency tree is a directed, connected, acyclic graph with words as nodes and _dependency-head_-relations as edges. Semantically, it reflects a sentence's dependency structure: Each word is linked to the head of the phrase that it is part of. There is always exactly one word that does not itself have a head. This word is called the _root_ of the sentence. For additional specification, the edges of such a dependency tree are often annotated with a label taken from a pre-defined set of possible dependency relations.

Large collections of such dependency trees—so called _treebanks_—are being used in a number of linguistic subfields: In syntax they shed light on the possible sentence structures a language allows for; in grammar they help explain to what sort of agreement constraints words in a phrase are subjected to; and in linguistic typology, languages are classified and compared based on the prevailing patterns in word order.

One popular guideline for dependency annotation is the _Universal Dependencies_ (UD) framework. Its main proposition lies in the specification of conventions and tag sets for the annotation of parts of speech, morphological features, and dependency relations that are universal enough to be applicable to virtually all natural languages. Currently, the official UD collection contains 353 treebanks for 193 different languages. UD also defines the CoNLL-U file format used for storing annotated sentences and entire treebanks along with metadata in a machine-readable manner. In this format, sentences are represented as tables with one row for every token/word and ten columns holding the annotations: `ID`, `FORM`, `LEMMA`, `UPOS`, `XPOS`, `FEATS`, `HEAD`, `DEPREL`, `DEPS`, and `MISC`. For now it suffices to know that `ID` is an integer index starting at 1, and that `HEAD` stores the `ID` of the word's head or `0` if it is the root. The type of dependency relation can be specified in `DEPREL` and `DEPS`.

The creation of a treebank like this typically requires a lot of manual labor. To reduce the work load as much as possible, many projects opt for a semi-automated approach, using a pre-trained tagger for intermediate annotations that, in a second step, get corrected by a human. For high-resource languages, taggers are available via all major NLP libraries (Stanza, SpaCy, NLTK), but for the majority of the world's roughly 7000 languages no such tools exist.

As the training of a tagger itself postulates the existence of a treebank to serve as training data, the problem of not having a pre-trained model is not one to be resolved easily. Additional challenges stem from the fact that many low resource languages have not undergone standardization and so the little amount of data that might be available displays high entropy, causing the training signal to be quite noisy. This throws annotators back into the situation of having to do everything by hand, which—depending on the availability of funding—can make the creation of a new treebank simply unaffordable.

But there is hope: The success of large language models (LLMs) as universal problem solvers gives us good reason to believe that the aforementioned bottle neck relating to manual labeling is indeed surmountable. More specifically, hundreds of treebanks can be assumed to be part of the data used for model training and even if a particular low-resource language is largely out of distribution, studies on cross-lingual transfer have shown that LLMs are reasonably good at extrapolating knowledge of a higher-resource language to a closely related low-resource language.

What makes dependency parsing nonetheless challenging is the topology of the problem: Dependency trees are inherently non-linear and dependency relations can stretch over long distances—conditions that LLMs are known to be less good at. The aim of this project is to measure the performance of smaller LLMs in the 7B–12B range on this task and to see if providing the model with different tools for example-retrieval, morphological analysis and lexicon look-ups has an impact on the output quality.
